#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle
#
#   For Windows, see gradlew.bat
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    expr "$link" : '/.*' > /dev/null
    if [ $id -eq 0 ] ; then
        APP_HOME="$link"
    else
        APP_HOME=`dirname "$PRG"`/"$link"
    fi
    PRG="$link"
done

APP_HOME=`dirname "$PRG"`

# Make APP_HOME absolute
APP_HOME=`cd "$APP_HOME" && pwd -P`

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD to a fixed value
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* | MSYS* )
    msys=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the java executable
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your path.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    
fi

# Increase the maximum file descriptors if we can
if [ "$cygwin" = "false" -a "$msys" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -="maximum" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n "$MAX_FD" 2>/dev/null
        if [ ! -z "$MAX_FD" ] ; then
            if [ "$MAX_FD_LIMIT" -lt "$MAX_FD" ] ; then
                warn "The current environment limits the maximum number of open files available to processes to $MAX_FD_LIMIT, which may compile or run slowly."
            fi
        fi
    fi
end

# Escape all characters, plus spaces and semicolons
save_arguments () {
    for i do
        case "$i" in
            *[!A-Za-z0-9_/:.-]*)
                safe_arg=`printf '%-0s' "$i" | sed "s/'/'\\\\''/g"`
                printf "'%s' " "$safe_arg"
                ;;
            *)
                printf '%s ' "$i"
                ;;
        esac
    done
}

# Collect all arguments for gradle
GRADLE_OPTS=`save_arguments "$@"`

# Determine the proper jar file to execute
JAR_FILE="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$JAR_FILE" ] ; then
    die "ERROR: Gradle wrapper jar not found at $JAR_FILE"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $GRADLE_OPTS -jar "$JAR_FILE" "$@"
